# Application Identity
spring.application.name=vihiga_fleet_backend
server.port=8080

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/vihiga_fleet
spring.datasource.username=postgres
spring.datasource.password=Klouseasava@2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations (Fixed to keep your data safe on restart)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=klouseasava2004@gmail.com
spring.mail.password=tofkksojeyktjrhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

# Custom Application Property for Sender Email
app.mail.from=klouseasava2004@gmail.com